### ISSUE TITLE
cpu_count didn't work

### ISSUE THREAD

**Issue by AnnieXuY** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#13]
Hello guys,
Thank you for providing this reference implementation. 
I did some test, and results of this project are indeed more accurate than vmaf. However time consuming is not an advantage.
I found that the project provides the --cpu_count parameter, but no matter what number is set, the actual cpu_count is still 1. I wonder if this is a bug?

The test environment was as follows：
Linux version 3.10.0-229.el7.x86_64  (gcc version 4.8.2 )
Python 3.6.6
cpu info: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
processor: 24
cpu cores	: 6

The command line  is as follows：
poetry run p1204_3 --cpu_count 4  test_videos/test.mp4

How do I set it up to enable multiprocessing to improve the efficiency of the program?

Looking forward to a response.

BR,
Annie

**Comment by slhck** [comment]
The CPU count parameter affects the parallel processing of many files. The way the parsing of bitstream information works is that it can only run single-threaded, so any parallelism must be achieved by calculating the scores on many video files or segments in parallel. I hope this clarifies your question.

**Comment by AnnieXuY** [comment]
I understand and thank you for your response.
