### ISSUE TITLE
Is there any recommended value or maximum value for the video duration

### ISSUE THREAD

**Issue by AnnieXuY** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#15]
Hello guys,
Thank you for providing this reference implementation.

When I enter a 10 minute video, it runs for an hour without quitting and I don't get any results. 
Is there any recommended value or maximum value for the video duration?

The test environment was as follows：
Linux version 3.10.0-229.el7.x86_64 (gcc version 4.8.2 )
Python 3.6.6
cpu info: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
processor: 24
cpu cores : 6

The command line is as follows：
poetry run p1204_3  test_videos/test.mp4

Looking forward to a response.

BR,
Annie

**Comment by slhck** [comment]
Please note that the standard is only validated for video segments of 6-8 seconds length. You can test shorter segments, too. For longer videos, you need to split up the file into smaller chunks first.

Hope this helps.

**Comment by AnnieXuY** [comment]
> Please note that the standard is only validated for video segments of 6-8 seconds length. You can test shorter segments, too. For longer videos, you need to split up the file into smaller chunks first.
> 
> Hope this helps.

Is there a maximum value for the duration of video segment?

**Comment by slhck** [comment]
Technically there is no maximum value, however, during standardization, only segments of up to ~8s length were tested. Our model predicts values for each second of input though, so you can in principle use longer segments as well – if you are purely interested in per-second and not overall quality. I would recommend not to use segments of more than 10s length though.

If you don't care about the final value being standards-compliant, you can run it on a longer file, but if you use a longer sequence, there are issues with memory consumption (see #16) which may prevent the script from executing successfully.

**Comment by AnnieXuY** [comment]
> Technically there is no maximum value, however, during standardization, only segments of up to ~8s length were tested. Our model predicts values for each second of input though, so you can in principle use longer segments as well – if you are purely interested in per-second and not overall quality. I would recommend not to use segments of more than 10s length though.
> 
> If you don't care about the final value being standards-compliant, you can run it on a longer file, but if you use a longer sequence, there are issues with memory consumption (see #16) which may prevent the script from executing successfully.

I got it and thank you for your response.
