### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by slhck** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#16]
See comment: https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3/issues/9#issuecomment-682404605

The per-frame values should be written as they are extracted from the parser, to a newline-delimited JSON file, one line per frame. This way, the per-frame info will not have to be kept in memory but can be written out immediately, and later the quality calculation can be optimized as well.

I suggest implementing this new method of writing the data in the bitstream-parser repo, and in order to make it backwards-compatible, in this code, where the data is read, it will simply check if it is an NDJSON file or a regular JSON file, and then decide whether to read line-by-line, or whether to read it as a whole.

**Comment by nanlilili** [comment]
HI~ Could I ask your a question about where is the G.1070 based video quality reference scoring integration source code? I want to study it,I got it from https://www.itu.int/itu-t/recommendations/rec.aspx?rec=13622&lang=en

**Comment by slhck** [comment]
There is no public source code implementation of G.1070 that I am aware of. If you want to use it you may have to implement it yourself based on the equations.

**Comment by nanlilili** [comment]
thank you very much~

**Comment by nanlilili** [comment]
> There is no public source code implementation of G.1070 that I am aware of. If you want to use it you may have to implement it yourself based on the equations.

thank you very much~

**Comment by nanlilili** [comment]
Excuse me~, i find a mistake about the project,i use two different video stream in the same name.The score is the same，but if i use  in the different name,the score is different.Do you use a name as a unique identifier?How can I avoid it？Look forward to your reply~

**Comment by slhck** [comment]
For each video a temporary cache file is created in tmp. You have to delete the temporary file to avoid the program using the same input again.

**Comment by nanlilili** [comment]
> For each video a temporary cache file is created in tmp. You have to delete the temporary file to avoid the program using the same input again.

oh I see it，thanks for you~

**Comment by stg7** [comment]
also related to https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3/issues/25

we are aware that the parser is not meant for production, and thus would require some speedup and simplification.

i will close this issue and add a comment to the other one, to streamline the issues a bit
