### ISSUE TITLE
about the relationship between per_sequence and video quality

### ISSUE THREAD

**Issue by AnnieXuY** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#17]
Hello guys,
Thank you for providing this reference implementation.

I'd like to ask a few questions about the relationship between per_sequence and video quality.

(1).How does per_sequence measure video quality? Is the meaning of the per_sequence score consistent with the meaning of the grading scale (as follows) in the ITU-R BT.500 standard?
The five-grade impairment scale:
5	imperceptible
4	perceptible, but not annoying
3	slightly annoying
2	annoying
1	very annoying

(2).How much of the per_sequence difference can represent subjective differences in the human visual system? Just like vmaf=6 probably represents a subjective difference ladder.

Looking forward to a response.

BR,
Annie

**Comment by slhck** [comment]
The rating corresponds to the Absolute Category Rating scale from ITU-T P.910, meaning:

1. Bad
2. Poor
3. Fair
4. Good
5. Excellent

About your second question, I have to check with my colleagues, as this is not a trivial issue. It primarily depends on the type of viewing that was used for the subjective tests: if the viewing was ACR, then the required difference in MOS will be greater; if it was a DSIS/DCR type rating (with the scale you mentioned), the MOS difference that subjects can determine will be smaller.

**Comment by AnnieXuY** [comment]
> The rating corresponds to the Absolute Category Rating scale from ITU-T P.910, meaning:
> 
> 1. Bad
> 2. Poor
> 3. Fair
> 4. Good
> 5. Excellent
> 
> About your second question, I have to check with my colleagues, as this is not a trivial issue. It primarily depends on the type of viewing that was used for the subjective tests: if the viewing was ACR, then the required difference in MOS will be greater; if it was a DSIS/DCR type rating (with the scale you mentioned), the MOS difference that subjects can determine will be smaller.

I agree that this is not a trivial issue. 
The actual usage is similar to ACR, can you first give the recommended MOS difference value when the viewing is ACR ? 
DCR is more suitable for theoretical studies, will you also give a reference MOS difference for DCR in the future?
Thanks

**Comment by slhck** [comment]
The model's error (RMSE) against subjective data is, on average, 0.37, so you can assume that any prediction difference < 0.37 is within the statistical uncertainty. Strictly speaking, two MOS scores less than 0.37 apart could, in theory, be considered statistically equivalent, but that does not mean that you cannot use the model in practice to compare sequences with an expected difference that is smaller.

Which kind of theoretical studies are you talking about in terms of DCR being more suitable?

About DCR-style predictions or some indication of what a Just Noticeable Difference (JND) is, this would require a different set of subjective tests with explicit references, and this is currently not planned. It is also not the main scope of bitstream-based models like this, as, if you have a reference, you usually would use a full-reference model. (That said, the predictions of P.1204.3 are comparable to state of the art full-reference models and even outperform VMAF, as [shown in our tech report](https://telecommunication-telemedia-assessment.github.io/bitstream_based_models/documents/tech-report-bitstream-based-models.pdf)).

I hope I could clarify some aspects. If you or anyone else has any pointers as to how to derive a JND for these kinds of ACR metrics, we'd be happy to hear about it.

**Comment by AnnieXuY** [comment]
Thank you very much for your response.
By theoretical studies I mean the data in most papers. However, in many practical scenarios, subjective evaluations are more like ACR.
I have tested some videos along with subjective comparisons. p.1204.3 does predict much better than VMAF. So I will continue to use P.1204.3 as an indicator of subjective assessment in my future experiments and studies.
If I run into problems again, I will come back to you for advice, thank you very much.

**Comment by slhck** [comment]
Thank you for your feedback!
