### ISSUE TITLE
Invalid data stream error

### ISSUE THREAD

**Issue by JoshuaEbenezer** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#23]
Hi, I'm getting the following error:
```
ERROR:root:there was a problem while processing video.mp4  
error:Invalid data stream
[
    {}
]
```
I was able to run the bitstream parser on the video without issues, so I'm not sure what's going on. I'm trying to debug it myself but if you've encountered this before please let me know.

**Comment by slhck** [comment]
Looks like an error if the data file is not a valid `.tar.bz2` file.

Make sure you deleted any cache files related to the video.

**Comment by JoshuaEbenezer** [comment]
Yes, thanks! I figured out the issue. There was a problem with the video file earlier and the bitstream parser had cached some incorrect results. I regenerated the video and was confused because the error still showed, but once I deleted the cached results from the earlier (incorrect) video everything worked fine. Closing.
